main/urls.py
from django.urls import path

from .views import index, profile, BBLogoutView, BBLoginView, ChangeUserInfoView, BBPasswordChangeView, RegisterUserView, RegisterDoneView
from .views import user_activate, DeleteUserView, profile_pt_add, profile_pt_change, profile_pt_delete, detail, guest_pt_add, contain_comment

app_name = 'main'
urlpatterns = [
    path('', index, name = 'index'),
    path("add/", guest_pt_add, name = 'guest_pt_add'),
    path('<int:pk>/', detail, name = 'detail'),
    path('comment<int:pk>/', contain_comment, name = 'contain_comment'),
    path('accounts/register/', RegisterUserView.as_view(), name = 'register'),
    path('account/login/', BBLoginView.as_view(), name = 'login'),
    path('account/logout/', BBLogoutView.as_view(), name = 'logout'),
    path('accounts/profile/', profile, name = 'profile'),
    path('accounts/profile/delete/', DeleteUserView.as_view(), name = 'profile_delete'),
    path('accounts/register/actvate/<str:sign>/', user_activate, name = 'register_activate'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name = 'register_done'),
    path('accounts/profile/change/<int:pk>/', profile_pt_change, name = 'profile_pt_change'),
    path('accounts/profile/delete/<int:pk>/', profile_pt_delete, name = 'profile_pt_delete'),
    path('accounts/profile/add/', profile_pt_add, name = 'profile_pt_add'),   
    path('accounts/password/change/', BBPasswordChangeView.as_view(), name = 'password_change'),
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name = 'profile_change'), 
]

rddt_clone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
from django.conf.urls.static import static


urlpatterns = [
    path('captcha/', include('captcha.urls')),
    path('', include('main.urls', namespace='')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.dispatch import Signal

from .utilities import send_activation_notification, get_timestamp_path

class AdvUser(AbstractUser):
	is_activated = models.BooleanField(default = True, db_index = True, verbose_name = 'Прошел активацию?')
	telephone = models.CharField(max_length =12, verbose_name = 'Номер телефона')
	anketa = models.TextField(verbose_name = 'О себе')

	class Meta(AbstractUser.Meta):
		pass

class Pt(models.Model):

	title = models.CharField(max_length = 50, verbose_name = 'Заголовок')
	author = models.CharField(max_length = 50, verbose_name = 'Автор')
	content = models.TextField(verbose_name = 'Статья')
	created_at = models.DateTimeField(auto_now_add = True, db_index = True, verbose_name = 'Опубликовано')
	image = models.ImageField(blank = True, upload_to = get_timestamp_path, verbose_name = 'Изображение')
	is_active = models.BooleanField(default = True, db_index = True, verbose_name = 'Выводить на экран?')
	
	class Meta:
		verbose_name = 'Статья'
		verbose_name_plural = "Статьи"
		ordering = ['-created_at']
	
user_registrated = Signal(providing_args=['instance'])

def user_registrated_dispatcher(sender, **kwargs):
	send_activation_notification(kwargs['instance'])

user_registrated.connect(user_registrated_dispatcher)

class Comment(models.Model):
	pt = models.ForeignKey(Pt, on_delete = models.CASCADE, verbose_name = 'Статья')
	author = models.CharField(max_length = 50, db_index = True, verbose_name = 'Автор')
	content = models.TextField(verbose_name = 'Комментарий')
	is_active = models.BooleanField(default = True, db_index = True, verbose_name = 'Выводить на экран?')
	created_at = models.DateTimeField(auto_now_add = True, db_index = True, verbose_name = 'Опубликован')

	class Meta:
		verbose_name_plural = 'Комментарии'
		verbose_name = 'Комментарий'
		ordering = ['-created_at']

class Comment_to_comment(models.Model):
	key = models.ForeignKey(Comment, on_delete = models.CASCADE)
	author = models.CharField(max_length = 50, verbose_name = 'Автор')
	content = models.TextField(verbose_name = 'Комментарий')
	is_active = models.BooleanField(default = True, db_index = True, verbose_name = 'Выводить на экран?')
	created_at = models.DateTimeField(auto_now_add = True, db_index = True, verbose_name = 'Опубликован')

	class Meta:
		verbose_name_plural = 'Комментарии 2-го порядка'
		verbose_name = 'Комментарий 2-го порядка'
		ordering = ['-created_at']

main/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from captcha.fields import CaptchaField

from .models import AdvUser, user_registrated, Pt, Comment, Comment_to_comment

class ChangeUserInfoForm(forms.ModelForm):
	email = forms.EmailField(required = True, label = 'Адрес электронной почты')

	class Meta:
	    model = AdvUser
	    fields = ('email', 'first_name', 'last_name', 'telephone', 'anketa')		

class RegisterUserForm(forms.ModelForm):
	email = forms.EmailField(required = True, label = 'Адрес электронной почты')
	password1 = forms.CharField(label = 'Пароль', widget = forms.PasswordInput, 
		help_text = "Пароль не должен быть простым и содержать вашу персональную информацию. Ваш пароль должен содержать минимум 8 символов.")
	password2 = forms.CharField(label = 'Пароль (повторно)', widget = forms.PasswordInput,
		help_text = 'Ведите тот же самый пароль ещё раз для проверки')


	def clean_password(self):
		password1 = self.cleaned_data['password1']
		if password1:
			password_validation.validate_password(password1)
		return password1

	def clean(self):
		super().clean()
		password1 = self.cleaned_data['password1']
		password2 = self.cleaned_data['password2']
		if password1 and password2 and password1 != password2:
			errors = {'password2': ValidationError('Ведённые пароли не совпадают', code = 'password_mismatch')}
			raise ValidationError(errors)

	def save(self, commit = True):
		user = super().save(commit = False)
		user.set_password(self.cleaned_data['password1'])
		user.is_active = False
		user.is_activated = False
		if commit:
			user.save()
		user_registrated.send(RegisterUserForm, instance = user)
		return user

	class Meta:
		model = AdvUser
		fields = ('username','email','password1','password2','first_name','last_name',)

class PtForm(forms.ModelForm):
	class Meta:
		model = Pt
		fields = '__all__'
		widgets = {'is_active': forms.HiddenInput, 'author': forms.HiddenInput}

class UserCommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		exclude = ('is_active',)
		widgets = {'pt': forms.HiddenInput, 'author': forms.HiddenInput}

class GuestCommentForm(forms.ModelForm):
	captcha = CaptchaField(label = 'ВВедите текст с картинки', error_messages = {'invalid': 'Неправильный текст'})

	class Meta:
		model = Comment
		fields = '__all__'
		widgets = {'pt': forms.HiddenInput, 'author': forms.HiddenInput, 'is_active': forms.HiddenInput}

class User_CommentForm(forms.ModelForm):
	class Meta:
		model = Comment_to_comment
		exclude = ('is_active',)
		widgets = {'key': forms.HiddenInput, 'pt': forms.HiddenInput, 'author': forms.HiddenInput}

class Guest_CommentForm(forms.ModelForm):
	captcha = CaptchaField(label = 'ВВедите текст с картинки', error_messages = {'invalid': 'Неправильный текст'})

	class Meta:
		model = Comment_to_comment
		fields = '__all__'
		widgets = {'key': forms.HiddenInput, 'author': forms.HiddenInput, 'is_active': forms.HiddenInput}

main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.core.signing import BadSignature
from django.contrib.auth import logout
from django.contrib import messages
from django.core.paginator import Paginator

from .models import AdvUser, Pt,  Comment, Comment_to_comment
from .forms import ChangeUserInfoForm, RegisterUserForm, PtForm, UserCommentForm, GuestCommentForm, User_CommentForm, Guest_CommentForm  
from .utilities import signer

def index (request):
	pts = Pt.objects.filter(is_active = True)
	paginator = Paginator(pts, 2)

	page_number = request.GET.get('page', 1)
	page = paginator.get_page(page_number)

	context = {'pts': page}
	return render(request, 'main/index.html', context)

class BBLoginView(LoginView):
	template_name = 'main/login.html'

@login_required
def profile(request):
	pts = Pt.objects.filter(author = request.user.username)
	context = {'pts': pts}
	return render(request, 'main/profile.html', context)

class BBLogoutView(LoginRequiredMixin, LogoutView):
	template_name = 'main/logout.html'

class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
	model = AdvUser
	template_name = 'main/change_user_info.html'
	form_class = ChangeUserInfoForm
	success_url = reverse_lazy('main:profile')
	
	def dispatch(self, request, *args, **kwargs):
		self.user_id =request.user.pk
		return super().dispatch(request, *args, **kwargs)

	def get_object(self, queryset = None):
		if not queryset:
			queryset = self.get_queryset()
		return get_object_or_404(queryset, pk = self.user_id)

class BBPasswordChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
	template_name = 'main/password_change.html'
	success_url = reverse_lazy('main:password_change')
	success_message = 'Пароль успешно изменён'
	
class RegisterUserView(CreateView):
	model = AdvUser
	template_name = 'main/register_user.html'
	form_class = RegisterUserForm
	success_url = reverse_lazy('main:register_done')

class RegisterDoneView(TemplateView):
	template_name = 'main/register_done.html'

def user_activate(request, sign):
	try:
		username = signer.unsign(sign)
	except BadSignature:
		return render(request, 'main/bad_signature.html')
	user = get_object_or_404(AdvUser, username = username)
	if user.is_activated:
		template = 'main/user_is_activated.html'
	else:
		template = 'main/activation_done.html'
		user.is_active = True
		user.is_activated = True
		user.save()
	return render(request, template)

class DeleteUserView(LoginRequiredMixin, DeleteView):
	model = AdvUser
	template_name = 'main/delete_user.html'
	success_url = reverse_lazy('main:index')

	def dispatch(self, request, *args, **kwargs):
		self.user_id = request.user.pk
		return super().dispatch(request, *args, **kwargs)

	def post(self, request, *args, **kwargs):
		logout(request)
		return super().post(request, *args, **kwargs)

	def get_object(self, queryset = None):
		if not queryset:
			queryset = self.get_queryset()
		return get_object_or_404(queryset, pk = self.user_id)


@login_required
def profile_pt_add(request):
	if request.method == 'POST':
		form = PtForm(request.POST, request.FILES, initial = {'author': request.user.username})
		if form.is_valid():
			pt = form.save()
			messages.add_message(request, messages.SUCCESS, 'Статья добавлена')
			return redirect('main:profile_pt_add')
	else:
		form = PtForm(initial = {'author': request.user.username})
	context = {'form': form}
	return render(request, 'main/profile_pt_add.html', context)	

@login_required
def profile_pt_change(request, pk):
	pt = get_object_or_404(Pt, pk = pk)
	if request.method == 'POST':
		form = PtForm(request.POST, request.FILES, instance = pt)
		if form.is_valid():
			pt = form.save()
			return redirect('main:profile')
	else:
		form = PtForm(instance = pt)
		context = {'form':form}
		return render(request, 'main/profile_pt_change.html', context)

@login_required
def profile_pt_delete(request, pk):
	pt = get_object_or_404(Pt, pk = pk)
	if request.method == 'POST':
		pt.delete()
		return redirect('main:profile')
	else:
	    context = {'pt': pt}
	    return render(request, 'main/profile_pt_delete.html', context)

def detail (request, pk):
	pt = Pt.objects.get(pk = pk)
	comments = Comment.objects.filter(pt = pk, is_active = True)
	initial = {'pt': pt.pk}
	if request.user.is_authenticated:
		initial['author'] = request.user.username
		form_class = UserCommentForm
	else:
		initial['author'] = "Незарегистрированный пользователь"
		initial['is_active'] = False
		form_class = GuestCommentForm
	form = form_class(initial = initial)
	if request.method == 'POST':
		c_form = form_class(request.POST)
		if c_form.is_valid():
			c_form.save()
			messages.add_message(request, messages.SUCCESS, 'Комментарий добавлен')
		else:
			form = c_form
			messages.add_message(request, messages.WARNING, 'Комментарий не добавлен')
	context = {'pt': pt, 'comments': comments, 'form': form}
	return render(request, 'main/detail.html', context)

def guest_pt_add(request):
	if request.method == 'POST':
		form = PtForm(request.POST, request.FILES, initial = {'author': 'Незарегистрированный пользователь', 'is_active': False})
		if form.is_valid():
			pt = form.save()
			messages.add_message(request, messages.SUCCESS, 'Статья будет отображена на сайте после прохождения процесса модерации')
			return redirect('main:guest_pt_add')
	else:
		form = PtForm(initial = {'author': 'Незарегистрированный пользователь', 'is_active': False})
	context = {'form': form}
	return render(request, 'main/guest_pt_add.html', context)

def contain_comment (request, pk):
	comment = Comment.objects.get(pk = pk)
	coms = Comment_to_comment.objects.filter(key_id = pk, is_active = True)
	initial = {'comment': comment.pk}
	if request.user.is_authenticated:
		initial['author'] = request.user.username
		initial['key'] = comment.pk
		form_class = User_CommentForm
	else:
		initial['author'] = "Незарегистрированный пользователь"
		initial['is_active'] = False
		initial['key'] = comment.pk
		form_class = Guest_CommentForm
	form = form_class(initial = initial)
	if request.method == 'POST':
		c_form = form_class(request.POST)
		if c_form.is_valid():
			c_form.save()
			messages.add_message(request, messages.SUCCESS, 'Комментарий добавлен')
		else:
			form = c_form
			messages.add_message(request, messages.WARNING, 'Комментарий не добавлен')
	context = {'coms': coms, 'comment': comment, 'form': form}
	return render(request, 'main/contain_comment.html', context)	

main/templates/main/bad_signature.html
{% extends "layout/basic.html" %}

{% block title %}Ошибка при активации{% endblock %}

{% block content %}
<h2>Активация</h2>
<p>Учетная запись пользователя не активирована.</p>
<p><a href="{% url 'main:register' %}">Зарегистрироваться повторно</a></p>
{% endblock %}

main/templates/main/change_user_info.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Правка личных данных{% endblock %}

{% block content %}
<h2>Правка личных данных пользователя {{ user.username }}</h2>
<form method="post">
	{% csrf_token %}
	{% bootstrap_form form layout='horizontal' %}
	{% buttons submit='Сохранить' %}{% endbuttons %}
</form>
{% endblock %}

main/templates/main/contain_comment.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}{{ pt.title }}{% endblock %}

{% block content %}
<div class="container-fluid mt-3">
	<div class="row">
		
		<div class="col">
			<h2>{{ comment.author }}</h2>
			<p>{{ comment.content }}</p>

		</div>
	</div>
</div>
<h4 class="mt-5">Новый комментарий</h4>

{% if messages %}
    {% for message in messages %}
        <font color="gren" size="5"><p col {% if message.tags %} class="{{message.tags}}"{% endif %}>{{message}}</p></font>
    {% endfor %}
{% endif %}

<form method="post">
	{% csrf_token %}
	{% bootstrap_form form layout='horizontal' %}
	{% buttons submit='Добавить' %}{% endbuttons %}
</form>
<h3>Комментарии</h3>

{% if coms %}
<div class="mt-5">
	{% for com in coms %}
	<div class="my-2 p-2 border">
		<h5>{{ com.author }}</h5>
		<p>{{ com.content }}</p>
		<p class="text-right font-italic">{{ com.created_at }}</p>
	</div>
	{% endfor %}
</div>
{% endif %}

{% endblock %}

main/templates/main/delete_user.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Удаление пользователя{% endblock %}

{% block content %}
<h2>Удаления пользователя {{ object.username }}</h2>
<form method="post">
	{% csrf_token %}
	{% buttons submit='Удалить' %}{% endbuttons %}
</form>
{% endblock %}

main/templates/main/detail.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}{{ pt.title }}{% endblock %}

{% block content %}
<div class="container-fluid mt-3">
	<div class="row">
		{% if pt.image %}
		<div class="col-md-auto"><img src="{{ pt.image.url }}" class="main-image"></div>
		{% endif %}
		<div class="col">
			<h2>{{ pt.title }}</h2>
			<p>{{ pt.content }}</p>

		</div>
	</div>
</div>
<h4 class="mt-5">Новый комментарий</h4>
{% if messages %}
    {% for message in messages %}
        <font color="gren" size="5"><p col {% if message.tags %} class="{{message.tags}}"{% endif %}>{{message}}</p></font>
    {% endfor %}
{% endif %}
<form method="post">
	{% csrf_token %}
	{% bootstrap_form form layout='horizontal' %}
	{% buttons submit='Добавить' %}{% endbuttons %}
</form>
{% if comments %}
<div class="mt-5">
	{% for comment in comments %}
	<div class="my-2 p-2 border">
		<h5>{{ comment.author }}</h5>
		<p>{{ comment.content }}</p>
		<p class="text-right font-italic">{{ comment.created_at }}</p>
		<a href="{% url 'main:contain_comment' pk=comment.pk %}"><input type="submit" value="Ответить"/></a>
	</div>
	{% endfor %}
</div>
{% endif %}
{% endblock %}

main/templates/main/guest_pt_add.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Добавление новой статьи{% endblock %}

{% block content %}
<h2>Добавление новой статьи</h2>
{% if messages %}
    {% for message in messages %}
        <font color="gren" size="5"><p col {% if message.tags %} class="{{message.tags}}"{% endif %}>{{message}}</p></font>
    {% endfor %}
{% endif %}
<form method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{% bootstrap_form form layout='horizontal' %}
	{% buttons submit='Добавить' %}{% endbuttons %}
</form>
{% endblock %}

main/templates/main/index.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Новые статьи{% endblock %}

{% block content %}
    <h3>Новые статьи</h3>
    {% if pts %}
        {% for pt in pts.object_list %}
        <div class="my-2 p-2 border">
            <h6>{{ pt.author }}</h6>
            <h6>{{ pt.created_at }}</h6>
            <a href="{% url 'main:detail' pk=pt.pk %}"><h3>{{ pt.title }}</h3></a>
            <p>{{ pt.content }}</p>
            {% if pt.image %}
                <div class="col-md-auto"><img src="{{ pt.image.url }}" class="main-image" width="150px"></div>
            {% endif %}
        </div>
        {% endfor %}
        <nav aria-label="...">
            <ul class="pagination pagination-sm">
            {% for n in pts.paginator.page_range %}
                {% if pts.number == n %}
                    <li class="page-item disabled">
                        <a class="page-link" href="?page={{ n }}" tabindex="-1">{{ n }}</a>
                    </li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ n }}">{{ n }}</a></li>
                {% endif %} 
            {% endfor %}       
            </ul>
        </nav>
    {% endif %}
{% endblock %}

main/templates/main/logout.html
{% extends "layout/basic.html" %}

{% block title %}Выход{% endblock %}

{% block content %}
<h2>Выход</h2>
<p>Вы успешно вышли с сайта.</p>
{% endblock %}

main/templates/main/profile.html
{% extends "layout/basic.html" %}

{% block title %}Профиль пользователя{% endblock %}

{% block content %}
    <h2>Профиль пользователя {{ user.username }}</h2>
    {% if user.first_name and user.last_name %}
        <p>Здравствуйте, {{ user.first_name }} {{ user.last_name }}!</p>
    {% else %}
        <p>Здравствуйте!</p>
    {% endif %}
    <p><a href="{% url 'main:profile_pt_add' %}">Добавить статью</a></p>
    <h3>Ваши статьи</h3>
    {% if pts %}
    <ul class="list-unstyled">
        {% for pt in pts %}
        <li class="media my-5 p-3 border">
            <div class="media-body">
            <h6>{{ pt.created_at }}</h6>
            <a href="{% url 'main:detail' pk=pt.pk %}"><h3>{{ pt.title }}</h3></a> 
            <a href="{% url 'main:profile_pt_change' pt.pk %}"><input type="submit" value="Исправить"/></a> 
            <a href="{% url 'main:profile_pt_delete' pt.pk %}"><input type="submit" value="Удалить"/></a>         
    	    </div>      	          
        </li>
        {% endfor %}
    {% endif %}    
    </ul>  
    
{% endblock %}

main/templates/main/profile_pt_add.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Добавление новой статьи{% endblock %}

{% block content %}
<h2>Добавление новой статьи</h2>
{% if messages %}
    {% for message in messages %}
        <font color="gren" size="5"><p col {% if message.tags %} class="{{message.tags}}"{% endif %}>{{message}}</p></font>
    {% endfor %}
{% endif %}
<form method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{% bootstrap_form form layout='horizontal' %}
	{% buttons submit='Добавить' %}{% endbuttons %}
</form>
{% endblock %}

main/templates/main/profile_pt_change.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Правка статьи{% endblock %}

{% block content %}
<h2>Правка статьи пользователя{{ user.username }}</h2>
<form method="post">
	{% csrf_token %}
	{% bootstrap_form form layout='horizontal' %}
	{% buttons submit='Сохранить' %}{% endbuttons %}
</form>
{% endblock %}

main/templates/main/profile_pt_delete.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Удаление статьи{% endblock %}

{% block content %}
<h2>Удаления статьи {{ object.username }}</h2>
<form method="post">
	{% csrf_token %}
	{% buttons submit='Удалить' %}{% endbuttons %}
</form>
{% endblock %}

main/templates/main/register_done.html
{% extends "layout/basic.html" %}

{% block title %}Регистрация завершена{% endblock %}

{% block content %}
<h2>Регистрация</h2>
<p>Регистрация пользователя завершена</p>
{% endblock %}

main/templates/main/register_user.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Регистрация{% endblock %}

{% block content %}
<h2>Регистрация нового пользователя</h2>
<form method="post">
	{% csrf_token %}
	{% bootstrap_form form layout='horizontal' %}
	{% buttons submit='Зарегистрироваться' %}{% endbuttons %}
</form>
{% endblock %}